-- Home Sure — database schema
-- Import into the `homesure` MySQL database (already created via XAMPP/phpMyAdmin).
-- Covers: admin login, lead management (Quick Enquiry + Contact + full
-- Booking flow all land in one `leads` table), and the blog (posts +
-- categories). Run once; safe to re-run (CREATE TABLE IF NOT EXISTS).

SET NAMES utf8mb4;

-- ---------------------------------------------------------------------------
-- Admin users — one row per admin login. Seeded separately (see
-- admin/README or the setup step in todo.md) since the password hash has
-- to be generated by PHP's password_hash(), not hand-typed here.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  username VARCHAR(60) NOT NULL,
  email VARCHAR(150) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Leads — every submitted enquiry, from all 3 capture points on the public
-- site: the homepage Quick Enquiry mini-form, the Contact page form, and
-- the full appliance-page booking flow. `type` tells them apart; columns
-- that don't apply to a given type are simply left NULL (e.g. a quick
-- enquiry has no address/problem/slot).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS leads (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  booking_id VARCHAR(20) NULL,
  type ENUM('quick_enquiry','contact','booking') NOT NULL DEFAULT 'quick_enquiry',
  name VARCHAR(120) NOT NULL,
  mobile VARCHAR(15) NOT NULL,
  email VARCHAR(150) NULL,
  service VARCHAR(100) NULL,
  appliance_type VARCHAR(100) NULL,
  brand VARCHAR(100) NULL,
  problem TEXT NULL,
  address TEXT NULL,
  landmark VARCHAR(255) NULL,
  area VARCHAR(100) NULL,
  lat DECIMAL(10,7) NULL,
  lng DECIMAL(10,7) NULL,
  preferred_date DATE NULL,
  preferred_slot VARCHAR(50) NULL,
  is_emergency TINYINT(1) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  message TEXT NULL,
  status ENUM('New','Assigned','In Progress','Completed','Cancelled') NOT NULL DEFAULT 'New',
  technician_name VARCHAR(120) NULL,
  ip_address VARCHAR(45) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_booking_id (booking_id),
  KEY idx_status (status),
  KEY idx_service (service),
  KEY idx_created (created_at),
  KEY idx_mobile (mobile),
  KEY idx_technician (technician_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Migration note: this column/index was added 2026-08-14, after some
-- databases were already created from an earlier version of this file.
-- CREATE TABLE IF NOT EXISTS won't retrofit an existing `leads` table, so
-- if you're re-running this file against a pre-existing DB, run this once:
--   ALTER TABLE leads ADD COLUMN technician_name VARCHAR(120) NULL AFTER status;
--   ALTER TABLE leads ADD KEY idx_technician (technician_name);

-- ---------------------------------------------------------------------------
-- Technicians — managed from admin/technicians.php, offered as a dropdown
-- when assigning a lead (leads.technician_name stores the chosen name as
-- plain text, not a foreign key — simplest option that still gets you a
-- dropdown instead of free typing, and means deleting a technician later
-- doesn't touch already-assigned leads).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS technicians (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Migration note: added 2026-08-15, same situation as technician_name
-- above — CREATE TABLE IF NOT EXISTS only helps on a database that doesn't
-- already have `leads`/`blog_posts` etc. On an existing DB, just run the
-- CREATE TABLE statement above on its own; it's a new table so there's
-- nothing to retrofit.

-- ---------------------------------------------------------------------------
-- Blog
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS blog_categories (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  slug VARCHAR(80) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blog_posts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(220) NOT NULL,
  category_id INT UNSIGNED NULL,
  excerpt VARCHAR(500) NULL,
  content LONGTEXT NOT NULL,
  image_url VARCHAR(255) NULL,
  author VARCHAR(100) NOT NULL DEFAULT 'Home Sure Team',
  status ENUM('draft','published') NOT NULL DEFAULT 'published',
  published_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_slug (slug),
  KEY idx_status (status),
  CONSTRAINT fk_blog_category FOREIGN KEY (category_id) REFERENCES blog_categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Seed data — 3 blog categories + the 3 posts that were previously
-- hardcoded in includes/blog-data.php, so the blog doesn't look empty the
-- moment it goes live/DB-driven. Safe to edit/delete from the admin panel
-- afterwards.
-- ---------------------------------------------------------------------------
INSERT INTO blog_categories (name, slug) VALUES
  ('AC Care', 'ac-care'),
  ('Refrigerator', 'refrigerator'),
  ('Washing Machine', 'washing-machine')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO blog_posts (title, slug, category_id, excerpt, content, author, status, published_at) VALUES
(
  '5 Signs Your AC Needs Servicing Before Summer',
  'signs-your-ac-needs-servicing',
  (SELECT id FROM blog_categories WHERE slug = 'ac-care'),
  'Weak cooling, strange noises, and bad odors are early warning signs — here''s what to watch for before peak summer hits.',
  '<p>Bengaluru summers put real strain on air conditioners that haven\'t been serviced since last year. Here are five signs it\'s time to book a checkup before the heat peaks.</p><p>Weak or warm airflow, unusual noises during startup, a musty smell when the AC kicks in, visible water leakage near the indoor unit, and higher-than-usual electricity bills are all early indicators of a unit that needs attention. Catching these early usually means a simple service call instead of an emergency repair mid-summer.</p>',
  'Home Sure Team', 'published', '2026-03-12 10:00:00'
),
(
  'How to Extend Your Refrigerator''s Lifespan',
  'extend-refrigerator-lifespan',
  (SELECT id FROM blog_categories WHERE slug = 'refrigerator'),
  'A few simple habits can add years to your refrigerator''s working life and keep your energy bills down.',
  '<p>A well-maintained refrigerator can easily run for 12-15 years. Simple habits make a real difference: keep the coils dust-free, don\'t overpack shelves (airflow matters), check door seals for gaps, and avoid setting the thermostat colder than necessary.</p><p>If you notice your fridge running louder than usual or struggling to stay cold, don\'t wait — small issues caught early are far cheaper to fix than a full compressor failure later.</p>',
  'Home Sure Team', 'published', '2026-03-04 10:00:00'
),
(
  'Washing Machine Maintenance Tips for Monsoon Season',
  'washing-machine-maintenance-monsoon',
  (SELECT id FROM blog_categories WHERE slug = 'washing-machine'),
  'Humidity and power fluctuations during monsoon can be tough on washing machines — here''s how to protect yours.',
  '<p>Monsoon season in Bengaluru brings humidity and power fluctuations that can affect your washing machine\'s electronics and drainage system. Keep the machine covered when not in use, ensure the drainage hose has a clear, downward path, and consider a stabilizer if your area sees frequent voltage fluctuations.</p><p>If you notice the drum taking longer to drain or unusual odors during monsoon months, it\'s often a sign of a partially blocked drain — a quick and inexpensive fix if caught early.</p>',
  'Home Sure Team', 'published', '2026-02-21 10:00:00'
)
ON DUPLICATE KEY UPDATE title = VALUES(title);
